### PR TITLE
v0.19.0, updated version pinnings and added missing dependencies

### PR DESCRIPTION
**Pull request by danschef**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by danschef** [comment]
@conda-forge-admin, please rerender

**Comment by danschef** [comment]
@unbohn Just FYI, this currently fails with `isofit 1.1.3 has requirement xxhash>=1.2.0, but you have xxhash 0.0.0` during `pip check`. I will disable the check now as everything seems to run fine.

However, conda installs a quite old version of isofit (1.1.6) which seems to be due to tensorflow which is not available for Python 3.11, yet.

**Comment by unbohn** [comment]
@danschef Ok, thanks for solving this issue! Do you necessarily need to run the tests with Python 3.11? As you mentioned, ISOFIT is currently only running on Python 3.8 to 3.10 due to some packages being not available on 3.11. However, the SICOR feedstock checks should work fine also with newer versions of ISOFIT. As a future option, you could try to pin ISOFIT to a minimum version, e.g., v2.9.5, and add `xxhash >= 1.2.0` to the SICOR requirements. Note that we're installing xxhash with pip instead of conda, after running into some issues there.

**Comment by danschef** [comment]
@unbohn 
Looks like the `you have xxhash 0.0.0` error is some kind of packaging error at `python-xxhash>3` (maybe due to https://github.com/ifduyue/python-xxhash/issues/55) and goes away when pinning `python-xxhash` to `<3` which could be done [here](https://github.com/conda-forge/isofit-feedstock/blob/f40fbdf7e0e22b4419c76bc01ec39c304d9ab2b3/recipe/meta.yaml#L29). This should be reported at https://github.com/ifduyue/python-xxhash/issues.

However, when I pin isofit to `>=2.9.5`, pip check fails with these messages:

```
isofit 2.9.8 requires ndsplines, which is not installed.
isofit 2.9.8 requires ray, which is not installed.
isofit 2.9.8 has requirement protobuf~=3.19.0, but you have protobuf 4.21.12.
```
The first two are because ndsplines and ray are listed [in the setup.cfg of isofit](https://github.com/isofit/isofit/blob/main/setup.cfg) but [not in the feedstock recipe](https://github.com/conda-forge/isofit-feedstock/blob/main/recipe/meta.yaml#L29). The last one does not make sense to me but you could easily avoid it by changing [this line](https://github.com/isofit/isofit/blob/7e176f5c8038cbb0145b77ca4a3c578889e0b475/setup.cfg#L29) to `protobuf>3.19.0`.

BTW: setuptools is a Python-builtin package and not a run requirement as listed [here](https://github.com/conda-forge/isofit-feedstock/blob/f40fbdf7e0e22b4419c76bc01ec39c304d9ab2b3/recipe/meta.yaml#L34). I guess also pytest and pep8 are test requirements which should be labelled as such in https://github.com/isofit/isofit/blob/main/setup.cfg and excluded from the run requirements in the conda recipe. Probably, it would also make sense to add a `pip check` to the isofit conda recipe.

**Comment by unbohn** [comment]
@danschef Thanks for looking into the details! These are some good suggestions, which I'll consider to implement soon. However, the problem with ray is challenging because the versions on conda-forge are maintained by the community, not the ray developer. Installing it from conda was not stable at all for us and the developer themselves recommend to install it from PyPi. To my knowledge, it's not a good practice to include pip packages in a conda feedstock recipe. Or have you done this before?

**Pull request merged**
