### PR TITLE
Drop Python 3.6, drop folium, update URL.

### PR DESCRIPTION
**Pull request by danschef**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by danschef** [comment]
@conda-forge-admin please rerender

**Comment by danschef** [comment]
@niklasbohn
As sicor could not be installed with Python 3.11, I re-rendered the feedstock, dropped the old Python 3.6, and updated the GitLab URL. Also the folium pinning is not needed anymore here because sicor does not depend on folium and the pinning is implemented upstream in arosics.

Here is what I got when trying to install sicor + Python 3.11:

```
(base) gfz-fe@geoms:~$ mamba create -n sicor_py311 "sicor" "python=3.11"

Looking for: ['sicor', 'python=3.11']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
file:///home/gfz-fe/.conda_channels_local/pygfz/..   4.5kB @  42.3MB/s  0.0s
file:///home/gfz-fe/.conda_channels_local/pygfz/.. 103.0 B @   1.7MB/s  0.0s
file:///home/gfz-fe/.conda_channels_local/pygfz/..   4.5kB @  62.8MB/s  0.0s
file:///home/gfz-fe/.conda_channels_local/pygfz/.. 103.0 B @   1.9MB/s  0.0s
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/linux-64                                            No change
Could not solve for environment specs
Encountered problems while solving:
  - package sicor-0.14.6.1-pyh87b5ea3_0 requires gdal >=3.0.4,<3.1.0a0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by danschef** [comment]
As all checks are green, I merge this now.

**Comment by danschef** [comment]
Ok, sicor is still not installable with Python 3.11, because numba is not yet available for 3.11.

```
Could not solve for environment specs
Encountered problems while solving:
  - package sicor-0.18.0-pyhd8ed1ab_0 requires numba, but none of the providers can be installed
```

**Comment by danschef** [comment]
@unbohn Did you change your user name? Probably, you should update it in the meta.yaml then.

**Comment by niklasbohn** [comment]
@danschef Thanks for updating this! I actually do have two active Github accounts associated with different email addresses. I'll still use the @niklasbohn account for all activities related to SICOR.

**Pull request merged**
