### PR TITLE
Bump isofit.

### PR DESCRIPTION
**Pull request by danschef**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by danschef** [comment]
@conda-forge-admin, please rerender

**Comment by danschef** [comment]
@unbohn
I just pinned `isofit` to `>=2.10` here because the enpt build [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=839554&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) picks an old isofit version and isofit is not a direct dependency of enpt. I also added a `pip check` which still fails [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=839588&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) due to `ndsplines` and `protobuf`:

```bash
+ pip check
isofit 2.10.2 requires ndsplines, which is not installed.
isofit 2.10.2 has requirement protobuf~=3.19.0, but you have protobuf 4.21.12.
```


With a look to the isofit repo, it seems like protobuf was recently removed entirely. However, v2.10.2 (latest version) still has it: https://github.com/isofit/isofit/blob/148c78041981a1a0ef2a249a3352062752298605/setup.cfg#L29.

Could you release a new version of isofit that includes the removed protobuf?

**Comment by unbohn** [comment]
@danschef Thanks for the reminder! I'm working on getting the new release out. For now, we removed `ndsplines` entirely as it's not necessarily required. However, if it turns out to appear on conda-forge someday, we could certainly think about re-adding it.

**Comment by danschef** [comment]
@conda-forge-admin, please rerender

**Comment by danschef** [comment]
@unbohn 
Thanks for pushing the new isofit release. In the meantime, we created a new feedstock for ndsplines in https://github.com/kb-press/ndsplines/issues/105 and the first conda-forge releases are just coming up. So if it makes your code easier, you could now easily re-activate your previous ndsplines implementation.

**Comment by unbohn** [comment]
Awesome, thanks for initiating this, @danschef! I'll work on getting `ndsplines` back in.

**Pull request merged**
